#version: '3'

services:
  # Run one of these two Astro services at a time by specifying it directly with the command
  # e.g., docker-compose up codex astro-dev

  # Astro Development Server
  astro-dev:
    image: node:22.16-alpine3.22 #node:18-alpine
    container_name: astro-dev
    working_dir: /app
    ports:
      - "4324:4321"  # Astro dev server with live changes port - Go to http://localhost:4324/
    volumes:
      - ./:/app
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    environment:
      - NODE_ENV=development
      - MODE=WAITING
      - HERO_TITLE_PREFIX="Time is valuable"
      - HERO_TITLE_HIGHLIGHT="Great Stuff"
      - HERO_TITLE_SUFFIX="is coming soon."
      - HERO_SUBTITLE="Don't waste it with the WRONT website."
      - HERO_IMAGE_PATH=/images/image1.webp
      - BYNUMBER_1_VALUE="12+"
      - BYNUMBER_1_LABEL="Created projects"
      - BYNUMBER_2_VALUE="200+"
      - BYNUMBER_2_LABEL="Projects"
      - BYNUMBER_3_VALUE="120"
      - BYNUMBER_3_LABEL="Happy Client"
      - BYNUMBER_4_VALUE="5++"
      - BYNUMBER_4_LABEL="Years"
      - FORM_URL="https://app.formbricks.com/s/cmdxm7avj0zgjw001z2q5qtp0"
      - FORM_EMAIL_FIELD_ID="gqoiwzjon6gyunyqxqd9wrtq"
    networks:
      - project-network
      - cloudflared_tunnel
    tty: true
    restart: "no"

  astro-prod:
    image: node:22.16-alpine3.22 #node:18-alpine #docker pull node:22.16-alpine3.22
    container_name: astro-prod
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "8087:4321"  # Changed to match Astro's default port
    command: >
      sh -c "npm install && npm run build && npx http-server ./dist -p 4321"
    environment:
      - NODE_ENV=production
    networks:
      - project-network
    restart: "no"

networks:
  project-network:
    name: project-waitingtolanding
  cloudflared_tunnel:
    external: true