[project]
name = "waiting-to-landing"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "questionary>=2.1.0",
    "requests>=2.32.4",
]
